#!/bin/zsh
# upgrade system using appropriate package manager

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	sudo apt-get upgrade
	if command -v snap; then
		sudo snap refresh
	fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
	brew upgrade
else
	echo "unsupported os $OSTYPE"
fi

