[[language]]
name="bash"
file-types = [
  "bash", 
  ".bashrc", 
  ".bash_aliases", 
  "sh", 
  "zsh", 
  ".zshrc", 
  ".zsh_aliases"
]

[[language]]
name = "cpp"
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["cc", "hh", "c++", "cpp", "hpp", "h", "cxx", "hxx"]
comment-token = "//"
language-servers = [ "clangd" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = [ "gopls" ]


[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG", "mkd", "mdwn", "mdown", "markdn", "mdtxt", "mdtext", "workbook"]
roots = [".marksman.toml"]
language-servers = [ "marksman" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "python"
scope = "source.python"
file-types = ["py"]
language-servers = ["pylsp", "ruff-lsp", "pyright"]

[[language]]
name="rust"
file-types = ["rs"]
language-servers = ["rust-analyzer"]

[[language]]
name = "markdown"
file-types = ["md", "markdown"]
language-servers = [ "marksman" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "toml"
scope = "source.toml"
injection-regex = "toml"
file-types = ["toml", "poetry.lock", "Cargo.lock"]
roots = []
comment-token = "#"
language-servers = [ "taplo" ]
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "toml"
source = { git = "https://github.com/ikatyang/tree-sitter-toml", rev = "7cff70bbcbbc62001b465603ca1ea88edd668704" }

[[language]]
name="typescript"
file-types = ["ts"]
language-servers = ["typescript-language-server"]

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml"]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }

[language-server]
bash-language-server = { command = "bash-language-server", args = ["start"] }
clangd = { command = "clangd-12" }
gopls = { command = "gopls" }
marksman = { command = "marksman", args = ["server"] }
pyright = { command = "pyright-langserver", args = ["stdio"]}
ruff-lsp = { command = "ruff-lsp", args = [] }
rust-analyzer = { command = "rust-analyzer", args = [] }
taplo = { command = "taplo", args = ["lsp", "stdio"] }
typescript-language-server = { command = "typescript-language-server", args = ["--stdio"]}
