[[language]]
name = "python"
scope = "source.python"
language-server = { command = "ruff-lsp" }
config = { settings = { args = [] } }

[[language]]
name="bash"
language-server = { command = "bash-language-server" }
file-types = [
  "bash", 
  ".bashrc", 
  ".bash_aliases", 
  "sh", 
  "zsh", 
  ".zshrc", 
  ".zsh_aliases"
]