[[language]]
name="bash"
file-types = [
  "bash", 
  ".bashrc", 
  ".bash_aliases", 
  "sh", 
  "zsh", 
  ".zshrc", 
  ".zsh_aliases"
]
language-servers = ["bash-language-server"]

[[language]]
name = "python"
scope = "source.python"
language-servers = ["ruff-lsp"]

[[language]]
name="rust"
file-types = ["rs"]
language-servers = ["rust-analyzer"]

[[language]]
name="typescript"
file-types = ["ts"]
language-servers = ["typescript-language-server"]

[language-server]
bash-language-server = { command = "bash-language-server", args = ["start"] }
ruff-lsp = { command = "ruff-lsp", args = [] }
rust-analyzer = { command = "rust-analyzer", args = [] }
typescript-language-server = { command = "typescript-language-server", args = ["--stdio"]}