[[language]]
name="bash"
file-types = [
  "bash", 
  ".bashrc", 
  ".bash_aliases", 
  "sh", 
  "zsh", 
  ".zshrc", 
  ".zsh_aliases"
]
language-servers = ["bash-language-server"]

[[language]]
name = "python"
scope = "source.python"
file-types = ["py"]
formatter = { command = "black", args = ["--quiet", "--line-length=80", "-"] }
auto-format = true
language-servers = ["pylsp", "ruff-lsp"]

[[language]]
name="rust"
file-types = ["rs"]
language-servers = ["rust-analyzer"]


[[language]]
name = "markdown"
file-types = ["md", "markdown"]
language-servers = [ "marksman" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name="typescript"
file-types = ["ts"]
language-servers = ["typescript-language-server"]

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml"]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }

[language-server]
bash-language-server = { command = "bash-language-server", args = ["start"] }
marksman = { command = "marksman", args = ["server"] }
ruff-lsp = { command = "ruff-lsp", args = [] }
rust-analyzer = { command = "rust-analyzer", args = [] }
typescript-language-server = { command = "typescript-language-server", args = ["--stdio"]}